# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import messages_pb2 as messages__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in messages_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SmartCityStub(object):
    """Definição do Serviço gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChangeState = channel.unary_unary(
                '/SmartCity/ChangeState',
                request_serializer=messages__pb2.ChangeStateRequest.SerializeToString,
                response_deserializer=messages__pb2.Query.FromString,
                _registered_method=True)
        self.StateDevice = channel.unary_unary(
                '/SmartCity/StateDevice',
                request_serializer=messages__pb2.StateDeviceRequest.SerializeToString,
                response_deserializer=messages__pb2.Query.FromString,
                _registered_method=True)


class SmartCityServicer(object):
    """Definição do Serviço gRPC
    """

    def ChangeState(self, request, context):
        """RPC para mudar o estado do dispositivo, usando a nova mensagem de requisição
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StateDevice(self, request, context):
        """RPC para consultar o estado do dispositivo, usando a nova mensagem de requisição
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartCityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChangeState': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeState,
                    request_deserializer=messages__pb2.ChangeStateRequest.FromString,
                    response_serializer=messages__pb2.Query.SerializeToString,
            ),
            'StateDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.StateDevice,
                    request_deserializer=messages__pb2.StateDeviceRequest.FromString,
                    response_serializer=messages__pb2.Query.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SmartCity', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('SmartCity', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SmartCity(object):
    """Definição do Serviço gRPC
    """

    @staticmethod
    def ChangeState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SmartCity/ChangeState',
            messages__pb2.ChangeStateRequest.SerializeToString,
            messages__pb2.Query.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StateDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/SmartCity/StateDevice',
            messages__pb2.StateDeviceRequest.SerializeToString,
            messages__pb2.Query.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
